### PR TITLE
fix UI in dashboard

### PR DESCRIPTION
**Pull request by Killig3110**
This pull request includes several changes to the `TransactionHistoryModel`, `BillRepository`, `IBillService`, `iStatisticsService`, `BillServiceImpl`, and `StatisticsServiceImpl` files to enhance functionality and improve code quality. The most important changes include replacing `java.sql.Date` with `java.util.Date`, adding new methods to handle bill statuses, and introducing validation constraints.

### Changes to bill status handling:

* [`src/main/java/gr/careplus4/repositories/BillRepository.java`](diffhunk://#diff-8817c5b6cde297c4aa18e026b226578562be9658bf35e6756b53c88678394ba1L37-R42): Added methods `findBillsByStatus` and `findBillsByStatus` with pagination, both requiring a non-empty status.
* [`src/main/java/gr/careplus4/services/IBillService.java`](diffhunk://#diff-27c90867bfca85006f252af588f3e44f435db674e0672335a85b4af5511b6cdfR66-R73): Added methods `countBillIsStatusAwaiting`, `countBillIsStatusShipping`, `findALl`, and `findBillsByStatus` with pagination to the `IBillService` interface.
* [`src/main/java/gr/careplus4/services/iStatisticsService.java`](diffhunk://#diff-91a14867053fd8322a7f8aac6a05196eb79b28466d4d11aef81ff357c5f96ac8R30-R33): Added methods `getTotalBillIsStatusAwaiting` and `getTotalBillIsStatusShipping` to the `iStatisticsService` interface.
* [`src/main/java/gr/careplus4/services/impl/BillServiceImpl.java`](diffhunk://#diff-f57fbd21c857876a039018352d3e1c874df17614a8fe6fcfd68f191b1116fd86R544-R565): Implemented methods `countBillIsStatusAwaiting`, `countBillIsStatusShipping`, `findALl`, and `findBillsByStatus` with pagination in the `BillServiceImpl` class.
* [`src/main/java/gr/careplus4/services/impl/StatisticsServiceImpl.java`](diffhunk://#diff-7037b5f7d8c3bc8793a000490efb79172b693c91dd78fa9297ebb0b5941935e4R73-R81): Implemented methods `getTotalBillIsStatusAwaiting` and `getTotalBillIsStatusShipping` in the `StatisticsServiceImpl` class.

### Other improvements:

* [`src/main/java/gr/careplus4/models/TransactionHistoryModel.java`](diffhunk://#diff-2fc9acbb6247be90ddd30747f02bed3cd499eb4477c112994881dbe5557fed82L8-R8): Replaced `java.sql.Date` with `java.util.Date` for better date handling.
* [`src/main/java/gr/careplus4/repositories/BillRepository.java`](diffhunk://#diff-8817c5b6cde297c4aa18e026b226578562be9658bf35e6756b53c88678394ba1R6): Added `NotEmpty` validation constraint to the `status` parameter in the new methods.

UI:
image
image

### CODE REVIEW

**Review by Binarosie — DISMISSED** [review]
oke, chạy thử data mới đi ông

**Comment by Killig3110** [comment]
sửa UI chỗ này:
image

**Review by Binarosie — APPROVED** [review]
oke

**Review by vanphatit — APPROVED** [review]
oke

**Pull request merged**
